import React from 'react'
import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { useNavigate } from "react-router-dom";
import "./Friends.css";
import hsrProfile from "../gameImages/hq720.jpg";
import lolImg from "../gameImages/lol-banner.webp";
import searchIcon from "../assets/searchIcon.png";
import unfriendIcon from "../assets/unfriendIcon.png";

// data for demo, the placeboUsers data is generated by AI
const placeboUsers = [
  {
    id: 1,
    username: "GamerNumberOne",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Aidan",
    description: "Casual player looking for duo partners"
  },
  {
    id: 2,
    username: "ProPlayer99",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=Luis",
    description: "Competitive gamer, top tier"
  },
  {
    id: 3,
    username: "NightOwl",
    avatar: "https://api.dicebear.com/9.x/adventurer-neutral/svg?seed=Adrian",
    description: "I play mostly at night"
  },
  {
    id: 4,
    username: "HSRenjoyer",
    avatar: hsrProfile,
    description: "I just need the last constellation..."
  },
  {
    id: 5,
    username: "RandomPerson",
    avatar: lolImg,
    description: "Hello! Need two teammates for rank"
  },
];

const Friends = () => {
    const [users, setUsers] = useState([]); // users expected to be type array 
    const [search, setSearch] = useState("")
    const [friendRequests, setFriendRequests] = useState([])
    const [showFriendRequests, setShowFriendRequests] = useState(false)

    // fetch the list of friends from backend upon page load
    useEffect(() => {
        const init = async () => {
            //const data = await getFriends();
            setUsers(placeboUsers); // switch to data later
        }
        init();
    }, []);

    const getFriends = async () =>  {
         try {
            const response = await fetch("...", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${localStorage.getItem("access_token")}`,
                },
                credentials: "include",
            });

            if (!response.ok) {
                throw new Error("Failed to fetch users")
            }

            const data = await response.json()
            console.log(data)
            return data
        
        } catch (error) {
            console.error("Error fetching users:", error)
        }
    }

    // sends a text obj as username and receives the matching user(s)
    const onSearchSubmit = async (text) => {
       try {
            console.log(text)
            const response = await fetch("...", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${localStorage.getItem("access_token")}`,
                },
                credentials: "include",
                body: JSON.stringify(text),
            });

            if (!response.ok) {
                throw new Error("Failed to fetch users")
            }

            const data = await response.json()
            console.log(data)
            setUsers(data)
        
        } catch (error) {
            console.error("Error fetching users:", error)
        }
    }

    const getFriendRequests = async () => {
        try {
            const response = await fetch("...", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${localStorage.getItem("access_token")}`,
                },
                credentials: "include",
            });

            if (!response.ok) {
                throw new Error("Failed to fetch users")
            }

            // sort endpoint responds with the list of users sorted with name or availability
            const data = await response.json()
            console.log(data)
            setFriendRequests(data)

        } catch (error) {
            console.error("Error fetching users:", error)
        }
    }
    
    return (
        <div className="layout-friends">
            <h1 className="title-friends">Player Connections</h1>
            <div className="top-bar">

                {/* Search bar on the left */}
                    {/*</div><img src={} className="filterIcon" alt="search" /> */}
                <div className="search-bar">
                    <img src={searchIcon} alt="search" className="search-icon" />

                    <input
                        type="text"
                        placeholder="Search players..."
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="search-input"
                    />
                </div>
                
                 {/* Friend request button on the right */}
                <button className="requests-button" onClick={() => setShowFriendRequests(true)}>
                    Friend Requests
                    {friendRequests.length > 0 && (
                        <span className="badge">{friendRequests.length}</span>
                    )}
                </button>
            </div>
            
            {/* For each returned user, map its attributes to a banner*/}
            <div className="user-layout-friends">
                {users.map((user) => (
                    <div className="friend-banners">

                        {/* rank on left of banner*/}
                        <div className="left-side-friends">
                        </div>

                        {/* other user info on right of banner*/}
                        <div className="right-side-friends">
                            <div className="user-content-friends">
                                <div className="top-row-friends">
                                    <img src={user.avatar} className="avatar-friends" />
                                    <h3 className="username">{user.username}</h3>
                                </div>

                                <div className="user-info-friends">
                                    <p className="description-friends">{user.description}</p>
                                </div>
                            </div>

                            <div className="message-wrapper-friends">
                                <button className="message-button-friends">Message</button>
                            </div>

                            <button class="unfriend">
                                <img src={unfriendIcon} className="unfriend-icon"/>
                            </button>
                        </div>
                    </div>
                ))} 
            </div>
            {/* If no users found */}
            {users.length === 0 && (
                <div className="empty-msg-friends">
                    <p>No friends found, visit the matchmaking page for more!</p>
                </div>
            )}
        </div>
    )
}

export default Friends