import React from 'react'
import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { useNavigate } from "react-router-dom";
import "./Matchmaking.css";
import GameScheduleBar from "../components/GameScheduleBar";
import valorantImg from "../gameImages/valorant-banner.jpg";
import pubgImg from "../gameImages/pubg-banner.jpg";
import lolImg from "../gameImages/lol-banner.webp";
import minecraftImg from "../gameImages/minecraft.webp";
import sdtdImg from "../gameImages/7dtd.webp";
import hsrProfile from "../gameImages/hq720.jpg";
import RegionIcon from "../gameImages/map-5.png";
import filterIcon from "../gameImages/filterIcon.png";
import apexImg from "../gameImages/apex.jpg";
import sortIcon from "../gameImages/sortIcon.png";
import gameIcon from "../gameImages/gameIcon.png";
import PUAddFriend from '../components/PopupAddFriend';

// data for demo, the placeboUsers data is generated by AI
const placeboUsers = [
  {
    id: 1,
    username: "GamerNumberOne",
    rank: "Gold",
    region: "NA",
    avatar: "https://api.dicebear.com/9.x/adventurer/svg?seed=Aidan",
    description: "Casual player looking for duo partners",
    game: "Valorant"
  },
  {
    id: 2,
    username: "ProPlayer99",
    rank: "Diamond",
    region: "EU",
    avatar: "https://api.dicebear.com/9.x/lorelei-neutral/svg?seed=Luis",
    description: "Competitive gamer, top tier",
    game: "League"
  },
  {
    id: 3,
    username: "NightOwl",
    rank: "Pro",
    region: "ASIA",
    avatar: "https://api.dicebear.com/9.x/adventurer-neutral/svg?seed=Adrian",
    description: "I play mostly at night",
    game: "Minecraft"
  },
  {
    id: 4,
    username: "HSRenjoyer",
    rank: "Platinum",
    region: "ASIA",
    avatar: hsrProfile,
    description: "I just need the last constellation...",
    game: "PUBG"
  },
  {
    id: 5,
    username: "RandomPerson",
    rank: "Immortal",
    region: "NA",
    avatar: lolImg,
    description: "Hello! Need two teammates for rank",
    game: "Valorant"
  },
];

const gameImages = {
  Valorant: valorantImg,
  PUBG: pubgImg,
  League: lolImg,
  Minecraft: minecraftImg,
  sdtd: sdtdImg,
  "Apex Legends": apexImg,
};

const Matchmaking = () => {
    let user_list = [];
    const [users, setUsers] = useState([]); // users expected to be type array
    const [game, setGame] = useState("all") // default all 
    const [rank, setRank] = useState("all")
    const [role, setRole] = useState("all")
    const [sort, setSort] = useState("none")
    const [showPU1, setShowPU1] = useState(false)
    const [selectedUsername, setSelectedUsername] = useState(null)
    const [selectedUserid, setSelectedUserid] = useState(null)

    //const [showAvailability, setShowAvailability] = useState(false);

    // const days = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];

    // map the game for each user to background images for each game
    const attachGameImages = (users) => {
        const newUsers = [];

        for (let i = 0; i < users.length; i++) {
            const user = users[i];
            let image = gameImages[user.game];

            if (!image) {
                image = ""; // no img if not found
            }
            user.gameImage = image;
            newUsers.push(user);
        }
        return newUsers;
    };

    // if "all" is selected, filter is null. Else, add selected filter to obj
    const buildFilterObj = async () => {
        return {
            filters:{
                game: game === "all" ? null : game,
                rank: rank === "all" ? null : rank,
                role: role === "all" ? null : role,
            }
        }
    } 

    const buildSortObj = async () => {
        return {
            sort: sort,
            users: user_list
        }
    }

    // fetch the list of recommended users from backend upon page load, no sorting applied yet
    useEffect(() => {
        const init = async () => {
            const filters = await buildFilterObj();
            const data = await onFilterSubmit(filters);
            setUsers(attachGameImages(data));
        }
        init();
    }, []);

    const handleApplyFilters = async () =>  {
        const filters = await buildFilterObj();
        const filteredUsers = await onFilterSubmit(filters);

        if (sort === "none"){
            setUsers(attachGameImages(filteredUsers))
        }else{
            const sorts = await buildSortObj();
            onSortSubmit(sorts)
        }
    }

    // sends a filter obj with other info and receives recommended users from backend
    // filters can be empty or has actual values
    const onFilterSubmit = async (filters) => {
       try {
            console.log(filters)
            const response = await fetch("/api/user/filters", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${localStorage.getItem("access_token")}`,
                },
                credentials: "include",
                body: JSON.stringify(filters),
            });

            if (!response.ok) {
                throw new Error("Failed to fetch users")
            }

            const data = await response.json()
            user_list = data
            console.log(data)
            return data
        
        } catch (error) {
            console.error("Error fetching users:", error)
        }
    }

    const onSortSubmit = async (sortObj) => {
        try {
            console.log(sortObj)
            const response = await fetch("/api/user/sort", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${localStorage.getItem("access_token")}`,
                },
                credentials: "include",
                body: JSON.stringify(sortObj),
            });

            if (!response.ok) {
                throw new Error("Failed to fetch users")
            }

            // sort endpoint responds with the list of users sorted with name or availability
            const data = await response.json()
            console.log(data)
            setUsers(attachGameImages(data))

        } catch (error) {
            console.error("Error fetching users:", error)
        }
    }
    
    return (
        <div className="layout">
            <h1 className="title">Connect with Others</h1>
            <div className="filters-layout">

                {/* filter components */}
                <div className = "filters">
                    
                    <div className ="filter-controls">

                        <div className="header">
                            <div className="header-div">
                                <img src={filterIcon} className="filterIcon"/>
                                <span> Filters </span>
                            </div>

                            <select value={game} onChange={(e) => setGame(e.target.value)}>
                                <option value="all">All Games &#9662;</option>
                                <option value="League">League of Legends</option>
                                <option value="Valorant">Valorant</option>
                                <option value="Minecraft">Minecraft</option>
                                <option value="PUBG">PUBG</option>
                                <option value="7dtd">7dtd</option>
                                <option value="Apex">Apex Legends</option>
                            </select>
                        </div>

                        <select value={rank} onChange={(e) => setRank(e.target.value)}>
                            <option value="all">All Ranks &#9662;</option>
                            <option value="Bronze">Bronze</option>
                            <option value="Silver">Silver</option>
                            <option value="Gold">Gold</option>
                            <option value="Platinum">Platinum</option>
                            <option value="Diamond">Diamond</option>
                            <option value="Master">Master</option>
                        </select>

                        <select value={role} onChange={(e) => setRole(e.target.value)}>
                            <option value="all">All Roles &#9662; </option>
                            <option value="Support">Support</option>
                            <option value="DPS">DPS</option>
                            <option value="Tank">Tank</option>
                        </select>
                        
                        <div className="header">
                            <div className="header-div">
                                <img src={sortIcon} className="sortIcon"/>
                                <span> Sort By</span>
                            </div>
                            <select value={sort} onChange={(e) => setSort(e.target.value)}>
                                <option value="none"> None &#9662;</option>
                                <option value="availability">availability </option>
                                <option value="name">name</option>
                            </select>
                        </div>

                        {/* create button to show/hide availability filter
                        <div className="availability-dropdown">
                            <button className="availability-button" 
                                onClick={() => setShowAvailability(prev => !prev)}>
                                {showAvailability ? "Hide Availability" : "Set Availability ▾"}
                            </button>
                            {showAvailability && (
                                <div className="availability-content">
                                    <GameScheduleBar
                                        schedule={availability}
                                        onClick={handleAvailabilityToggle}
                                    />
                                </div>
                            )}
                        </div> */}
        
                        <button className="apply-button" onClick={handleApplyFilters}> Apply </button>
                    </div>
                </div>
            </div>
            
            {/* For each returned user, map its attributes to a banner*/}
            <PUAddFriend user={selectedUsername} user_id={selectedUserid} open={showPU1} onClose={() => setShowPU1(false)} />

            <div className="user-layout">
                {users.map((user) => (
                    <div className="user-banners">
                        {/* demo game img for different games*/}
                        <div className="bg-image" style={{ backgroundImage: `url(${user.gameImage})` }}>
                            <div className="bg-gradient-overlay" />
                        </div>

                        {/* rank on left of banner*/}
                        <div className="left-side">
                            <div className="rank">{user.rank}</div>
                        </div>

                        {/* other user info on right of banner*/}
                        <div className="right-side">
                            <div className="user-content">
                                <div className="top-row">
                                    <img src={user.avatar} className="avatar" />
                                    <h3 className="username">{user.username}</h3>
                                </div>

                                <div className="user-info">
                                    <p className="description">{user.description}</p>
                                    <div className="game-role">
                                        <img src={gameIcon}></img>
                                        <span className="text-gray-300"> {user.game} </span>
                                        <img src={RegionIcon} />
                                        <span className="text-gray-300"> {user.roles}</span>
                                    </div>
                                </div>
                            </div>

                            <div className="connect-wrapper" onClick={() => {
                                setSelectedUsername(user.username); 
                                setSelectedUserid(user.id); 
                                setShowPU1(true);
                                }}>
                                <button className="connect-button">Connect</button>
                            </div>
                        </div>
                    </div>
                ))} 
            </div>
            {/* If no users found */}
            {users.length === 0 && (
                <div className="empty-msg">
                    <p>No users found matching your filters</p>
                </div>
            )}
        </div>
    )
}

export default Matchmaking